# Generated by Django 5.1 on 2024-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblFaceLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('bottom', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, null=True)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_invalid', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_face_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFaceMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_face_id', models.IntegerField(blank=True, null=True)),
                ('face_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_invalid', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_face_matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblIdentities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_identities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblImageTensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('tensor_shape', models.TextField(blank=True, null=True)),
                ('tensor_pil', models.BinaryField(blank=True, null=True)),
                ('hash_pil', models.TextField(blank=True, null=True)),
                ('tensor_cv2', models.BinaryField(blank=True, null=True)),
                ('hash_cv2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_image_tensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblKnownFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
            ],
            options={
                'db_table': 'tbl_known_faces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMediaMetadata',
            fields=[
                ('media_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('exif_tag', models.CharField(blank=True, max_length=60, null=True)),
                ('exif_data', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_media_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMediaObjects',
            fields=[
                ('media_object_id', models.AutoField(primary_key=True, serialize=False)),
                ('orig_name', models.CharField(max_length=120)),
                ('new_name', models.CharField(blank=True, max_length=30, null=True)),
                ('new_path', models.CharField(blank=True, max_length=120, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('media_create_date', models.DateTimeField(blank=True, null=True)),
                ('location_class', models.CharField(blank=True, max_length=60, null=True)),
                ('location_type', models.CharField(blank=True, max_length=60, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=60, null=True)),
                ('location_province', models.CharField(blank=True, max_length=60, null=True)),
                ('location_country', models.CharField(blank=True, max_length=60, null=True)),
                ('tag_assigned', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_media_objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMovieHashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('media_hash', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_movie_hashes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=60, unique=True)),
                ('tag_desc', models.CharField(blank=True, max_length=120, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTagsToMedia',
            fields=[
                ('tags_to_media_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_tags_to_media',
                'managed': False,
            },
        ),
    ]
